const APIPRODUCTS = [
  {
    Product_ID: "PGSOFT2",
    Product_Name: "PG Soft",
    Description: "PG Soft",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "SLOTXO",
    Product_Name: "Slotxo",
    Description: "Slotxo",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "ASKMEBET",
    Product_Name: "Askmebet",
    Description: "Askmebet",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "HABANERO",
    Product_Name: "Habanero",
    Description: "Habanero",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "SPADE",
    Product_Name: "Spade Gaming",
    Description: "Spade Gaming",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "MICRO",
    Product_Name: "Micro Gaming",
    Description: "Micro Gaming",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "SIMPLEPLAY",
    Product_Name: "Simple Play",
    Description: "Simple Play",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "ICONIC",
    Product_Name: "Iconic Gaming",
    Description: "Iconic Gaming",
    Seamless: "-",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "MEGA",
    Product_Name: "Mega888",
    Description: "Mega888",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "XIN",
    Product_Name: "Xin Gaming",
    Description: "Xin Gaming",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "LIVE22",
    Product_Name: "Live22",
    Description: "Live22",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "GAMATRON",
    Product_Name: "Gamatron",
    Description: "Gamatron",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "ALLWAYSPIN",
    Product_Name: "Allwayspin",
    Description: "Allwayspin",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "FUN",
    Product_Name: "Fun Gaming",
    Description: "Fun Gaming",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "EURASIAN",
    Product_Name: "Eurasian Gaming",
    Description: "Eurasian Gaming",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "AMBPOKER",
    Product_Name: "Ambpoker",
    Description: "Ambpoker",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "JDB",
    Product_Name: "JDB",
    Description: "JDB",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "WAZDAN",
    Product_Name: "Wazdan",
    Description: "Wazdan",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "EVOPLAY",
    Product_Name: "Evoplay",
    Description: "Evoplay",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "ENDORPHINA",
    Product_Name: "Endorphina",
    Description: "Endorphina",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "CQ9",
    Product_Name: "CQ9",
    Description: "CQ9",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "KAGAME",
    Product_Name: "KA Gaming",
    Description: "KA Gaming",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "JILI",
    Product_Name: "Jili",
    Description: "Jili",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "JOKER",
    Product_Name: "Joker123",
    Description: "Joker123",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "MANNA",
    Product_Name: "Mannaplay",
    Description: "Mannaplay",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "NETENT",
    Product_Name: "Netent",
    Description: "Netent",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "TIGERGAME",
    Product_Name: "Tigergame",
    Description: "Tigergame",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "FUNKY2",
    Product_Name: "Funky Games",
    Description: "Funky Games",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "FUNKY",
    Product_Name: "Funky Games (deprecated)",
    Description: "Funky Games (deprecated)",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "YGGDRASIL",
    Product_Name: "Yggdrasil Gaming",
    Description: "Yggdrasil Gaming",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "UPG",
    Product_Name: "UPG Slot",
    Description: "UPG Slot",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "ROYAL",
    Product_Name: "Royal Slot Gaming",
    Description: "Royal Slot Gaming",
    Seamless: "-",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "GIOCO",
    Product_Name: "Gioco Plus",
    Description: "Gioco Plus",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "AMEBA",
    Product_Name: "Ameba",
    Description: "Ameba",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "AMBSLOT",
    Product_Name: "Ambslot",
    Description: "Ambslot",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "NETENT2",
    Product_Name: "Netent2",
    Description: "Netent2",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "PGSOFT",
    Product_Name: "Pgsoft (depecreated)",
    Description: "Pgsoft (depecreated)",
    Seamless: "-",
    Transfer: "✔",
    Category: "Games Slot",
  },
  {
    Product_ID: "RELAX",
    Product_Name: "Relax Gaming",
    Description: "Relax Gaming",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "REDTIGER",
    Product_Name: "Red Tiger",
    Description: "Red Tiger",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "DRAGONGAMING",
    Product_Name: "Dragon Gaming",
    Description: "Dragon Gaming",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "ACE333",
    Product_Name: "Ace333",
    Description: "Ace333",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "I8",
    Product_Name: "I8",
    Description: "I8",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "WMSLOT",
    Product_Name: "WmSlot",
    Description: "Wmslot",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "SPINIX",
    Product_Name: "Spinix",
    Description: "Spinix",
    Seamless: "✔",
    Transfer: "-",
    Category: "Games Slot",
  },
  {
    Product_ID: "SEXY",
    Product_Name: "Sexy Gaming",
    Description: "Sexy Gaming",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Live Casino",
  },
  {
    Product_ID: "PRAGMATIC",
    Product_Name: "Pragmatic Play",
    Description: "Pragmatic Play",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Live Casino",
  },
  {
    Product_ID: "BIGGAME",
    Product_Name: "Big Gaming",
    Description: "Big Gaming",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Live Casino",
  },
  {
    Product_ID: "DREAM",
    Product_Name: "Dream Gaming",
    Description: "Dream Gaming",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Live Casino",
  },
  {
    Product_ID: "WM",
    Product_Name: "WM Casino",
    Description: "WM Casino",
    Seamless: "✔",
    Transfer: "-",
    Category: "Live Casino",
  },
  {
    Product_ID: "BETGAME",
    Product_Name: "BetgamesTV",
    Description: "BetgamesTV",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Live Casino",
  },
  {
    Product_ID: "EBET",
    Product_Name: "Ebet",
    Description: "Ebet",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Live Casino",
  },
  {
    Product_ID: "ALLBET",
    Product_Name: "AllBet",
    Description: "AllBet",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Live Casino",
  },
  {
    Product_ID: "AGGAME",
    Product_Name: "Asia Gaming AG",
    Description: "Asia Gaming AG",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Live Casino",
  },
  {
    Product_ID: "PRETTY",
    Product_Name: "Pretty Gaming",
    Description: "Pretty Gaming",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Live Casino",
  },
  {
    Product_ID: "SAGAME",
    Product_Name: "SA Gaming",
    Description: "SA Gaming",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Live Casino",
  },
  {
    Product_ID: "XTREME",
    Product_Name: "Xtreme Gaming",
    Description: "Xtreme Gaming",
    Seamless: "✔",
    Transfer: "✔",
    Category: "Live Casino",
  },
  {
    Product_ID: "SBO",
    Product_Name: "Sbobet",
    Description: "Sbobet",
    Seamless: "-",
    Transfer: "-",
    Category: "Sportbook",
  },
  {
    Product_ID: "IBC",
    Product_Name: "IBC",
    Description: "IBC",
    Seamless: "-",
    Transfer: "-",
    Category: "Sportbook",
  },
  {
    Product_ID: "BBIN",
    Product_Name: "BBIN",
    Description: "BBIN",
    Seamless: "-",
    Transfer: "-",
    Category: "Sportbook",
  },
  {
    Product_ID: "WBET",
    Product_Name: "WBET",
    Description: "WBET",
    Seamless: "-",
    Transfer: "-",
    Category: "Sportbook",
  },
  {
    Product_ID: "TFGAME",
    Product_Name: "TF Gaming",
    Description: "TF Gaming",
    Seamless: "-",
    Transfer: "-",
    Category: "Sportbook",
  },
  {
    Product_ID: "IAE",
    Product_Name: "IAEsports",
    Description: "IAEsports",
    Seamless: "-",
    Transfer: "-",
    Category: "Sportbook",
  },
  {
    Product_ID: "MSPORT",
    Product_Name: "M-Sport",
    Description: "M-Sport",
    Seamless: "-",
    Transfer: "✔",
    Category: "Sportbook",
  },
  {
    Product_ID: "COCKFIGHT",
    Product_Name: "Cockfight",
    Description: "Cockfight",
    Seamless: "✔",
    Transfer: "-",
    Category: "Sportbook",
  },
  {
    Product_ID: "KINGPOKER",
    Product_Name: "Kingpoker",
    Description: "Kingpoker",
    Seamless: "-",
    Transfer: "✔",
    Category: "Poker",
  },
  {
    Product_ID: "KINGMAKER",
    Product_Name: "King Maker",
    Description: "King Maker",
    Seamless: "✔",
    Transfer: "-",
    Category: "Poker",
  },
  {
    Product_ID: "HOTGRAPH",
    Product_Name: "Hotgraph",
    Description: "Hotgraph",
    Seamless: "✔",
    Transfer: "-",
    Category: "Trading",
  },
]

export default APIPRODUCTS
